import React, { useState, useEffect } from 'react';
import { 
  AudioLines, 
  Mic, 
  Shuffle, 
  History, 
  LogOut, 
  Sun, 
  Moon, 
  Download, 
  Link2, 
  Check, 
  Volume2, 
  Upload, 
  Music
} from 'lucide-react';

import { AudioWaveform } from '../components/AudioWaveform';
import { ProgressBar } from '../components/ProgressBar';

interface AudioFile {
  id: number;
  title: string;
  model_used: string;
  voice_name: string | null;
  cloudinary_url: string;
  duration: number;
  created_at: string;
}

interface DashboardProps {
  token: string;
  onLogout: () => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ token, onLogout }) => {
  const [activeTab, setActiveTab] = useState<'tts' | 'cloning' | 'blending'>('tts');
  const [isLightMode, setIsLightMode] = useState(false);
  const [history, setHistory] = useState<AudioFile[]>([]);
  const [copiedId, setCopiedId] = useState<number | null>(null);

  // Status/Progress Indicator States
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(0);
  const [statusText, setStatusText] = useState('');

  // Form States - TTS
  const [ttsText, setTtsText] = useState('Welcome to the future of open-source voice generation. Experience natural synthesized speech instantly.');
  const [ttsVoice, setTtsVoice] = useState('af_heart');
  const [ttsSpeed, setTtsSpeed] = useState(1.0);
  const [ttsPitch, setTtsPitch] = useState(1.0);

  // Form States - Cloning
  const [cloneText, setCloneText] = useState('Hello there, this is a demonstration of voice cloning using a short reference audio clip.');
  const [cloneVoiceName, setCloneVoiceName] = useState('Custom Clone');
  const [cloneFile, setCloneFile] = useState<File | null>(null);
  const [cloneDragActive, setCloneDragActive] = useState(false);

  // Form States - Blending
  const [blendMode, setBlendMode] = useState<'text' | 'file'>('text');
  const [blendText, setBlendText] = useState('This audio is generated by blending two different voices together.');
  const [blendVoice1, setBlendVoice1] = useState('af_heart');
  const [blendVoice2, setBlendVoice2] = useState('am_adam');
  const [blendFile1, setBlendFile1] = useState<File | null>(null);
  const [blendFile2, setBlendFile2] = useState<File | null>(null);
  const [blendRatio, setBlendRatio] = useState(0.5);

  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8000';

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const response = await fetch(`${API_URL}/api/history`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      if (response.ok) {
        const data = await response.json();
        setHistory(data);
      }
    } catch (err) {
      console.error('Error fetching history:', err);
    }
  };

  // Helper function to animate progress bar simulation
  const simulateProgress = (finishCallback: () => Promise<void>) => {
    setLoading(true);
    setProgress(0);
    setStatusText('Processing audio synthesis request...');

    let currentProgress = 0;
    const interval = setInterval(() => {
      if (currentProgress < 30) {
        currentProgress += Math.random() * 8;
        setStatusText('Uploading request files and payload...');
      } else if (currentProgress < 75) {
        currentProgress += Math.random() * 5;
        setStatusText('Running voice modeling engine locally...');
      } else if (currentProgress < 95) {
        currentProgress += Math.random() * 2;
        setStatusText('Hosting output waveform on storage system...');
      }
      setProgress(Math.min(currentProgress, 95));
    }, 150);

    finishCallback().finally(() => {
      clearInterval(interval);
      setProgress(100);
      setStatusText('Done!');
      setTimeout(() => {
        setLoading(false);
        setProgress(0);
      }, 500);
    });
  };

  const handleGenerateTTS = async (e: React.FormEvent) => {
    e.preventDefault();
    simulateProgress(async () => {
      try {
        const response = await fetch(`${API_URL}/api/tts/generate`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({
            text: ttsText,
            voice: ttsVoice,
            speed: ttsSpeed,
            pitch: ttsPitch
          })
        });
        if (response.ok) {
          await fetchHistory();
        } else {
          const err = await response.json();
          alert(err.detail || 'Failed to generate TTS');
        }
      } catch (err) {
        alert('Connection error');
      }
    });
  };

  const handleCloneVoice = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!cloneFile) {
      alert('Please upload a reference audio file first');
      return;
    }

    simulateProgress(async () => {
      try {
        const formData = new FormData();
        formData.append('text', cloneText);
        formData.append('voice_name', cloneVoiceName);
        formData.append('reference_file', cloneFile);

        const response = await fetch(`${API_URL}/api/voice-cloning/clone`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`
          },
          body: formData
        });

        if (response.ok) {
          await fetchHistory();
        } else {
          const err = await response.json();
          alert(err.detail || 'Voice cloning failed');
        }
      } catch (err) {
        alert('Connection error');
      }
    });
  };

  const handleBlendSpeech = async (e: React.FormEvent) => {
    e.preventDefault();
    if (blendMode === 'file' && (!blendFile1 || !blendFile2)) {
      alert('Please select both audio files to blend');
      return;
    }

    simulateProgress(async () => {
      try {
        const formData = new FormData();
        formData.append('blend_ratio', blendRatio.toString());

        if (blendMode === 'text') {
          formData.append('text', blendText);
          formData.append('voice1', blendVoice1);
          formData.append('voice2', blendVoice2);
        } else {
          if (blendFile1) formData.append('audio1', blendFile1);
          if (blendFile2) formData.append('audio2', blendFile2);
        }

        const response = await fetch(`${API_URL}/api/voice-mixing/blend`, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`
          },
          body: formData
        });

        if (response.ok) {
          await fetchHistory();
        } else {
          const err = await response.json();
          alert(err.detail || 'Voice mixing failed');
        }
      } catch (err) {
        alert('Connection error');
      }
    });
  };

  const toggleTheme = () => {
    const nextTheme = !isLightMode;
    setIsLightMode(nextTheme);
    if (nextTheme) {
      document.body.classList.add('light-mode');
    } else {
      document.body.classList.remove('light-mode');
    }
  };

  const copyToClipboard = (id: number, url: string) => {
    const fullUrl = url.startsWith('/') ? `${API_URL}${url}` : url;
    navigator.clipboard.writeText(fullUrl);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleDownload = (url: string, filename: string) => {
    const fullUrl = url.startsWith('/') ? `${API_URL}${url}` : url;
    const a = document.createElement('a');
    a.href = fullUrl;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setCloneDragActive(true);
    } else if (e.type === 'dragleave') {
      setCloneDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setCloneDragActive(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      setCloneFile(e.dataTransfer.files[0]);
    }
  };

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      {/* Top Navbar */}
      <nav className="glass-panel" style={{
        margin: '16px 24px',
        padding: '16px 24px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderRadius: '16px',
        zIndex: 10
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            background: 'var(--accent-gradient)',
            padding: '8px',
            borderRadius: '8px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            <AudioLines size={20} color="#fff" />
          </div>
          <span style={{ fontSize: '1.2rem', fontWeight: 700, fontFamily: 'var(--font-display)' }}>
            ElevenLabs Clone
          </span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <button 
            onClick={toggleTheme}
            style={{
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              color: 'var(--text-primary)',
              display: 'flex',
              alignItems: 'center'
            }}
          >
            {isLightMode ? <Moon size={20} /> : <Sun size={20} />}
          </button>
          
          <button 
            onClick={onLogout}
            className="btn-secondary"
            style={{ padding: '8px 16px', fontSize: '0.85rem' }}
          >
            <LogOut size={14} />
            Logout
          </button>
        </div>
      </nav>

      {/* Main Workspace Grid */}
      <div className="dashboard-grid">
        {/* Sidebar Nav */}
        <aside className="glass-panel" style={{
          padding: '24px',
          display: 'flex',
          flexDirection: 'column',
          gap: '12px',
          height: 'fit-content'
        }}>
          <h3 style={{ fontSize: '0.85rem', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '8px', textAlign: 'left' }}>
            Features
          </h3>
          <button 
            onClick={() => setActiveTab('tts')}
            className={activeTab === 'tts' ? 'btn-primary' : 'btn-secondary'}
            style={{ justifyContent: 'flex-start', width: '100%' }}
          >
            <AudioLines size={18} />
            Voice Generation
          </button>
          <button 
            onClick={() => setActiveTab('cloning')}
            className={activeTab === 'cloning' ? 'btn-primary' : 'btn-secondary'}
            style={{ justifyContent: 'flex-start', width: '100%' }}
          >
            <Mic size={18} />
            Voice Cloning
          </button>
          <button 
            onClick={() => setActiveTab('blending')}
            className={activeTab === 'blending' ? 'btn-primary' : 'btn-secondary'}
            style={{ justifyContent: 'flex-start', width: '100%' }}
          >
            <Shuffle size={18} />
            Voice Mixing
          </button>
        </aside>

        {/* Feature Panel Work Area */}
        <main style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          
          {/* Main Workspace Card */}
          <div className="glass-panel" style={{ padding: '32px' }}>
            
            {/* TAB 1: TTS Generation */}
            {activeTab === 'tts' && (
              <form onSubmit={handleGenerateTTS}>
                <h2 style={{ textAlign: 'left', marginBottom: '24px' }}>Kokoro Text-to-Speech</h2>
                
                <div className="form-group">
                  <label className="form-label">Prompt Text</label>
                  <textarea 
                    className="form-textarea"
                    placeholder="Enter text to speak..."
                    value={ttsText}
                    onChange={(e) => setTtsText(e.target.value)}
                    required
                  />
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '20px' }}>
                  <div className="form-group">
                    <label className="form-label">Model Voice</label>
                    <select 
                      className="form-select"
                      value={ttsVoice}
                      onChange={(e) => setTtsVoice(e.target.value)}
                    >
                      <option value="af_heart">af_heart (US Female)</option>
                      <option value="af_bella">af_bella (US Female)</option>
                      <option value="af_nicole">af_nicole (US Female)</option>
                      <option value="af_sarah">af_sarah (US Female)</option>
                      <option value="am_adam">am_adam (US Male)</option>
                      <option value="am_michael">am_michael (US Male)</option>
                      <option value="bf_emma">bf_emma (UK Female)</option>
                      <option value="bf_isabella">bf_isabella (UK Female)</option>
                      <option value="bm_george">bm_george (UK Male)</option>
                      <option value="bm_lewis">bm_lewis (UK Male)</option>
                    </select>
                  </div>

                  <div className="form-group" style={{ justifyContent: 'center' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                      <label className="form-label">Speed multiplier ({ttsSpeed}x)</label>
                    </div>
                    <div className="range-slider-container">
                      <input 
                        type="range" 
                        min="0.5" 
                        max="2.0" 
                        step="0.05"
                        className="range-slider"
                        value={ttsSpeed}
                        onChange={(e) => setTtsSpeed(parseFloat(e.target.value))}
                      />
                    </div>
                  </div>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '24px' }}>
                  <div className="form-group" style={{ justifyContent: 'center' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                      <label className="form-label">Pitch multiplier ({ttsPitch}x)</label>
                    </div>
                    <div className="range-slider-container">
                      <input 
                        type="range" 
                        min="0.5" 
                        max="2.0" 
                        step="0.05"
                        className="range-slider"
                        value={ttsPitch}
                        onChange={(e) => setTtsPitch(parseFloat(e.target.value))}
                      />
                    </div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'flex-end' }}>
                    <button type="submit" className="btn-primary" disabled={loading} style={{ width: '100%', padding: '14px' }}>
                      <Volume2 size={18} />
                      Generate Audio
                    </button>
                  </div>
                </div>
              </form>
            )}

            {/* TAB 2: Voice Cloning */}
            {activeTab === 'cloning' && (
              <form onSubmit={handleCloneVoice}>
                <h2 style={{ textAlign: 'left', marginBottom: '24px' }}>Pocket TTS Voice Cloning</h2>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '20px' }}>
                  {/* File Drag and Drop */}
                  <div className="form-group">
                    <label className="form-label">Reference Audio (5s Sample)</label>
                    <div 
                      className={`upload-dropzone ${cloneDragActive ? 'active' : ''}`}
                      onDragEnter={handleDrag}
                      onDragOver={handleDrag}
                      onDragLeave={handleDrag}
                      onDrop={handleDrop}
                      onClick={() => document.getElementById('ref-file-input')?.click()}
                    >
                      <Upload size={28} style={{ color: 'var(--accent-primary)' }} />
                      <div style={{ fontSize: '0.85rem' }}>
                        {cloneFile ? (
                          <span style={{ color: 'var(--success)', fontWeight: 600 }}>{cloneFile.name}</span>
                        ) : (
                          <span>Drag and drop WAV/MP3 or click to browse</span>
                        )}
                      </div>
                      <input 
                        id="ref-file-input"
                        type="file" 
                        accept="audio/*" 
                        style={{ display: 'none' }}
                        onChange={(e) => {
                          if (e.target.files && e.target.files[0]) {
                            setCloneFile(e.target.files[0]);
                          }
                        }}
                      />
                    </div>
                  </div>

                  {/* Clone Configuration */}
                  <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                    <div className="form-group">
                      <label className="form-label">Voice Name</label>
                      <input 
                        type="text" 
                        className="form-input" 
                        value={cloneVoiceName}
                        onChange={(e) => setCloneVoiceName(e.target.value)}
                        required
                      />
                    </div>
                    <div className="form-group" style={{ marginBottom: 0 }}>
                      <button type="submit" className="btn-primary" disabled={loading} style={{ width: '100%', padding: '14px' }}>
                        <Mic size={18} />
                        Clone Voice & Synthesize
                      </button>
                    </div>
                  </div>
                </div>

                <div className="form-group">
                  <label className="form-label">Synthesize Text Prompt</label>
                  <textarea 
                    className="form-textarea"
                    placeholder="Enter what the cloned voice should say..."
                    value={cloneText}
                    onChange={(e) => setCloneText(e.target.value)}
                    required
                  />
                </div>
              </form>
            )}

            {/* TAB 3: Voice Mixing / Blending */}
            {activeTab === 'blending' && (
              <form onSubmit={handleBlendSpeech}>
                <h2 style={{ textAlign: 'left', marginBottom: '8px' }}>Speech Blending Module</h2>
                <p style={{ textAlign: 'left', fontSize: '0.85rem', marginBottom: '24px' }}>
                  Combine and overlay multiple voices. Blend voice timbres to synthesize fresh styles.
                </p>

                {/* Sub Tab Selection */}
                <div style={{ display: 'flex', gap: '8px', marginBottom: '24px' }}>
                  <button 
                    type="button"
                    onClick={() => setBlendMode('text')}
                    className={blendMode === 'text' ? 'btn-primary' : 'btn-secondary'}
                    style={{ padding: '8px 16px', fontSize: '0.8rem' }}
                  >
                    Blend Two AI Voices
                  </button>
                  <button 
                    type="button"
                    onClick={() => setBlendMode('file')}
                    className={blendMode === 'file' ? 'btn-primary' : 'btn-secondary'}
                    style={{ padding: '8px 16px', fontSize: '0.8rem' }}
                  >
                    Blend Two Audio Tracks
                  </button>
                </div>

                {/* Blend Mode 1: Text Synthesis Blend */}
                {blendMode === 'text' && (
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '20px' }}>
                    <div className="form-group">
                      <label className="form-label">First Voice style (Voice A)</label>
                      <select 
                        className="form-select"
                        value={blendVoice1}
                        onChange={(e) => setBlendVoice1(e.target.value)}
                      >
                        <option value="af_heart">af_heart (US Female)</option>
                        <option value="af_bella">af_bella (US Female)</option>
                        <option value="af_nicole">af_nicole (US Female)</option>
                        <option value="af_sarah">af_sarah (US Female)</option>
                        <option value="am_adam">am_adam (US Male)</option>
                      </select>
                    </div>

                    <div className="form-group">
                      <label className="form-label">Second Voice style (Voice B)</label>
                      <select 
                        className="form-select"
                        value={blendVoice2}
                        onChange={(e) => setBlendVoice2(e.target.value)}
                      >
                        <option value="am_michael">am_michael (US Male)</option>
                        <option value="am_adam">am_adam (US Male)</option>
                        <option value="bf_emma">bf_emma (UK Female)</option>
                        <option value="bf_isabella">bf_isabella (UK Female)</option>
                        <option value="bm_george">bm_george (UK Male)</option>
                      </select>
                    </div>
                  </div>
                )}

                {/* Blend Mode 2: Audio File Blend */}
                {blendMode === 'file' && (
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '20px' }}>
                    <div className="form-group">
                      <label className="form-label">Audio Track A</label>
                      <div 
                        className="upload-dropzone"
                        onClick={() => document.getElementById('blend-file-1')?.click()}
                        style={{ padding: '15px' }}
                      >
                        <Music size={20} style={{ color: 'var(--accent-primary)' }} />
                        <div style={{ fontSize: '0.8rem' }}>
                          {blendFile1 ? <span style={{ color: 'var(--success)' }}>{blendFile1.name}</span> : <span>Track A</span>}
                        </div>
                        <input 
                          id="blend-file-1"
                          type="file" 
                          accept="audio/*" 
                          style={{ display: 'none' }}
                          onChange={(e) => e.target.files && setBlendFile1(e.target.files[0])}
                        />
                      </div>
                    </div>

                    <div className="form-group">
                      <label className="form-label">Audio Track B</label>
                      <div 
                        className="upload-dropzone"
                        onClick={() => document.getElementById('blend-file-2')?.click()}
                        style={{ padding: '15px' }}
                      >
                        <Music size={20} style={{ color: 'var(--accent-secondary)' }} />
                        <div style={{ fontSize: '0.8rem' }}>
                          {blendFile2 ? <span style={{ color: 'var(--success)' }}>{blendFile2.name}</span> : <span>Track B</span>}
                        </div>
                        <input 
                          id="blend-file-2"
                          type="file" 
                          accept="audio/*" 
                          style={{ display: 'none' }}
                          onChange={(e) => e.target.files && setBlendFile2(e.target.files[0])}
                        />
                      </div>
                    </div>
                  </div>
                )}

                {blendMode === 'text' && (
                  <div className="form-group">
                    <label className="form-label">Synthesize Text Prompt</label>
                    <textarea 
                      className="form-textarea"
                      placeholder="Enter text to generate and blend..."
                      value={blendText}
                      onChange={(e) => setBlendText(e.target.value)}
                      required
                    />
                  </div>
                )}

                {/* Blend Ratio Control */}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', alignItems: 'flex-end', marginTop: '20px' }}>
                  <div className="form-group" style={{ marginBottom: 0 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                      <label className="form-label">Blend Ratio ({Math.round(blendRatio*100)}% A / {Math.round((1-blendRatio)*100)}% B)</label>
                    </div>
                    <div className="range-slider-container">
                      <input 
                        type="range" 
                        min="0.0" 
                        max="1.0" 
                        step="0.05"
                        className="range-slider"
                        value={blendRatio}
                        onChange={(e) => setBlendRatio(parseFloat(e.target.value))}
                      />
                    </div>
                  </div>
                  <button type="submit" className="btn-primary" disabled={loading} style={{ width: '100%', padding: '14px' }}>
                    <Shuffle size={18} />
                    Blend Audios
                  </button>
                </div>
              </form>
            )}

            {/* Simulated progress indicator */}
            <ProgressBar progress={progress} statusText={statusText} visible={loading} />

          </div>

          {/* Recent Files Panel */}
          <div className="glass-panel" style={{ padding: '32px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <History size={20} style={{ color: 'var(--accent-primary)' }} />
                <h2 style={{ margin: 0 }}>Recent Files</h2>
              </div>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                {history.length} file{history.length !== 1 && 's'} generated
              </span>
            </div>

            {history.length === 0 ? (
              <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
                <Volume2 size={40} style={{ opacity: 0.3, marginBottom: '12px' }} />
                <p>No audio files generated yet. Synthesize your first voice track above!</p>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                {history.map((item) => {
                  const audioUrl = item.cloudinary_url.startsWith('/') ? `${API_URL}${item.cloudinary_url}` : item.cloudinary_url;
                  
                  return (
                    <div 
                      key={item.id} 
                      className="glass-panel" 
                      style={{ 
                        padding: '16px', 
                        display: 'grid', 
                        gridTemplateColumns: '1fr 240px',
                        gap: '20px',
                        alignItems: 'center',
                        background: 'rgba(255,255,255,0.01)'
                      }}
                    >
                      {/* Left: Metadata info */}
                      <div style={{ textAlign: 'left', overflow: 'hidden' }}>
                        <div style={{ fontWeight: 600, fontSize: '0.95rem', color: 'var(--text-primary)', textOverflow: 'ellipsis', overflow: 'hidden', whiteSpace: 'nowrap', marginBottom: '4px' }}>
                          {item.title}
                        </div>
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                          <span style={{ background: 'var(--bg-tertiary)', padding: '2px 8px', borderRadius: '4px' }}>
                            {item.model_used}
                          </span>
                          {item.voice_name && (
                            <span style={{ background: 'var(--bg-tertiary)', padding: '2px 8px', borderRadius: '4px' }}>
                              Voice: {item.voice_name}
                            </span>
                          )}
                          <span style={{ padding: '2px 4px' }}>
                            {new Date(item.created_at).toLocaleDateString()} {new Date(item.created_at).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                          </span>
                        </div>
                      </div>

                      {/* Right: Waveform visualizer & Action triggers */}
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', alignItems: 'stretch' }}>
                        <AudioWaveform audioUrl={audioUrl} duration={item.duration} />
                        
                        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px' }}>
                          <button
                            onClick={() => copyToClipboard(item.id, item.cloudinary_url)}
                            className="btn-secondary"
                            style={{ padding: '6px 12px', fontSize: '0.75rem', gap: '4px', flexGrow: 1 }}
                            title="Copy public URL"
                          >
                            {copiedId === item.id ? <Check size={12} style={{ color: 'var(--success)' }} /> : <Link2 size={12} />}
                            {copiedId === item.id ? 'Copied!' : 'Copy URL'}
                          </button>
                          
                          <button
                            onClick={() => handleDownload(item.cloudinary_url, `${item.title.replace(/[\s:]+/g, '_')}.wav`)}
                            className="btn-secondary"
                            style={{ padding: '6px 12px', fontSize: '0.75rem', gap: '4px' }}
                            title="Download WAV"
                          >
                            <Download size={12} />
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

        </main>
      </div>
    </div>
  );
};
